name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    # Job düzeyinde matriks
    strategy:
      matrix:
        release: [R2024a, R2024b]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MATLAB tests
        uses: matlab-actions/run-tests@v2
        with:
          release: ${{ matrix.release }}           # matriks değişkeni
          test-results-pdf: test-results/pdf-results.pdf

      - name: Upload comparison reports
        uses: actions/upload-artifact@v4
        with:
          name: diffreports
          path: test-results/*.pdf                 # ileri eğik çizgi
